version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: million
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build: ./backend
    depends_on:
      - db
    env_file: .env
    ports:
      - '4000:4000'

  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - '5173:5173'
    env_file: .env

volumes:
  db-data:
